version: "3.5"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1.8GB"

  api01:
    build: .
    network_mode: host
    depends_on:
      - db
    environment:
      - APP_PORT=3000
      - APP_DB_USERNAME=admin
      - APP_DB_PASSWORD=admin
      - APP_DB_NAME=rinha
      - APP_DB_HOST=localhost
      - APP_DB_PORT=5432
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"

  api02:
    build: .
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - APP_DB_USERNAME=admin
      - APP_DB_PASSWORD=admin
      - APP_DB_NAME=rinha
      - APP_DB_HOST=localhost
      - APP_DB_PORT=5432
    network_mode: host
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "0.5GB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.2GB"